%Transfer function coefficients
a4 =   C_e*C_h*C_i*C_s*R_ea*R_ih*R_is*R_ie;
a3 =   C_e*C_h*C_i*R_ea*R_ie*R_ih + ...
       C_e*C_h*C_s*R_ea*R_ie*R_ih + ...
       C_e*C_h*C_s*R_ea*R_ie*R_is + ...
       C_e*C_h*C_s*R_ea*R_ih*R_is + ...
       C_e*C_i*C_s*R_ea*R_ie*R_is + ...
       C_h*C_i*C_s*R_ea*R_ih*R_is + ...
       C_h*C_i*C_s*R_ie*R_ih*R_is;
a2 =   C_e*C_h*R_ea*R_ie + ...
       C_e*C_h*R_ea*R_ih + ...
       C_e*C_i*R_ea*R_ie + ...
       C_h*C_i*R_ea*R_ih + ...
       C_h*C_i*R_ie*R_ih + ...
       C_e*C_s*R_ea*R_ie + ...
       C_e*C_s*R_ea*R_is + ...
       C_h*C_s*R_ea*R_ih + ...
       C_h*C_s*R_ea*R_is + ...
       C_i*C_s*R_ea*R_is + ...
       C_h*C_s*R_ie*R_ih + ...
       C_h*C_s*R_ie*R_is + ...
       C_h*C_s*R_ih*R_is + ...
       C_i*C_s*R_ie*R_is;
a1 =   C_e*R_ea + ...
       C_h*R_ea + ...
       C_i*R_ea + ...
       C_h*R_ie + ...
       C_h*R_ih + ...
       C_i*R_ie + ...
       C_s*R_ea + ...
       C_s*R_ie + ...
       C_s*R_is;
a0 =   1;
b1_H = Phi_h*C_e*R_ea*R_ie;
b0_H = Phi_h*(R_ea + R_ie);
b1_a = C_h*R_ih;
b0_a = 1;
b2_s = A_w*(C_e*C_h*R_ea*R_ie*R_ih);
b1_s = A_w*(C_e*R_ea*R_ie + C_h*R_ea*R_ih + C_h*R_ie*R_ih) + A_e*R_ea*C_h*R_ih;
b0_s = A_w*(R_ea + R_ie) + A_e*R_ea;

% a3_hat = a3/a4;
% a2_hat = a2/a4;
% a1_hat = a1/a4;
% a0_hat = a0/a4;
% b1H_hat = b1_H/a4;
% b0H_hat = b0_H/a4;
% b1a_hat = b1_a/a4;
% b0a_hat = b0_a/a4;
% b2s_hat = b2_s/a4;
% b1s_hat = b1_s/a4;
% b0s_hat = b0_s/a4;
